name: WinRAR Keygen Secrets

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Generate key 
      shell: powershell
      run: bin/x64-Release/winrar-keygen.exe "${{secrets.TEXT1}}" "${{secrets.TEXT2}}" | Out-File -Encoding Big5 rarreg.key
      
    - name: Upload key
      uses: actions/upload-artifact@v4
      with:
        name: rarreg_file
        path: rarreg.key
        retention-days: 90
